In [21]:
import pandas as pd

In [22]:
pd.set_option('display.max_columns', None)

In [16]:
college_data = pd.read_csv('data/colleges.tsv', sep='\t', engine ='python', header=0)

In [25]:
data_def = pd.read_csv('data/data_dictionary.tsv', sep='\t', engine ='python', header=0)

In [29]:
data_def.head(50)

,variable_name,definition,category,type
0,id,Unit ID for institution,root,integer
1,institution_name,Institution name,school,autocomplete
2,city,City,school,autocomplete
3,state,State postcode,school,string
4,locale,Locale of institution City: Large (population ...,school,string
5,control,Control of institution Public Private nonprofi...,school,string
6,pred_deg,Predominant degree awarded 0 Not classi...,school,string
7,highest_degree,Highest degree awarded 0 Non-degree-gra...,school,character
8,historically_black,Flag for Historically Black College and Univer...,school,integer
9,men_only,Flag for men-only college,school,integer
10,women_only,Flag for women-only college,school,integer
11,sat_verbal_quartile_1,25th percentile of SAT scores at the instituti...,admissions,float
12,sat_verbal_quartile_2,Midpoint of SAT scores at the institution (cri...,admissions,float
13,sat_verbal_quartile_3,75th percentile of SAT scores at the instituti...,admissions,float
14,sat_math_quartile_1,25th percentile of SAT scores at the instituti...,admissions,float
15,sat_math_quartile_2,Midpoint of SAT scores at the institution (math),admissions,float
16,sat_math_quartile_3,75th percentile of SAT scores at the instituti...,admissions,float
17,sat_writing_quartile_1,25th percentile of SAT scores at the instituti...,admissions,float
18,sat_writing_quartile_2,Midpoint of SAT scores at the institution (wri...,admissions,float
19,sat_writing_quartile_3,75th percentile of SAT scores at the instituti...,admissions,float
20,agriculture_major_perc,"Percentage of degrees awarded in Agriculture, ...",academics,float
21,resources_major_perc,Percentage of degrees awarded in Natural Resou...,academics,float
22,architecture_major_perc,Percentage of degrees awarded in Architecture ...,academics,float
23,cultural_major_perc,"Percentage of degrees awarded in Area, Ethnic,...",academics,float
24,communications_major_perc,Percentage of degrees awarded in Communication...,academics,float
25,comm_tech_major_perc,Percentage of degrees awarded in Communication...,academics,float
26,computer_science_major_perc,Percentage of degrees awarded in Computer And ...,academics,float
27,culinary_major_perc,Percentage of degrees awarded in Personal And ...,academics,float
28,education_major_perc,Percentage of degrees awarded in Education.,academics,float
29,engineering_major_perc,Percentage of degrees awarded in Engineering.,academics,float
30,eng_tech_major_perc,Percentage of degrees awarded in Engineering T...,academics,float
31,language_major_perc,Percentage of degrees awarded in Foreign Langu...,academics,float
32,consumer_science_major_perc,Percentage of degrees awarded in Family And Co...,academics,float
33,law_major_perc,Percentage of degrees awarded in Legal Profess...,academics,float
34,english_major_perc,Percentage of degrees awarded in English Langu...,academics,float
35,liberal_arts_major_perc,Percentage of degrees awarded in Liberal Arts ...,academics,float
36,library_science_major_perc,Percentage of degrees awarded in Library Science.,academics,float
37,bio_science_major_perc,Percentage of degrees awarded in Biological An...,academics,float
38,math_stats_major_perc,Percentage of degrees awarded in Mathematics A...,academics,float
39,military_major_perc,Percentage of degrees awarded in Military Tech...,academics,float
40,interdiscipline_major_perc,Percentage of degrees awarded in Multi/Interdi...,academics,float
41,parks_rec_major_perc,"Percentage of degrees awarded in Parks, Recrea...",academics,float
42,philo_relig_major_perc,Percentage of degrees awarded in Philosophy An...,academics,float
43,theology_major_perc,Percentage of degrees awarded in Theology And ...,academics,float
44,phys_science_major_perc,Percentage of degrees awarded in Physical Scie...,academics,float
45,science_technician_major_perc,Percentage of degrees awarded in Science Techn...,academics,float
46,psych_major_perc,Percentage of degrees awarded in Psychology.,academics,float
47,protective_services_major_perc,Percentage of degrees awarded in Homeland Secu...,academics,float
48,public_admin_major_perc,Percentage of degrees awarded in Public Admini...,academics,float
49,social_science_major_perc,Percentage of degrees awarded in Social Sciences.,academics,float

In [36]:
data_def.tail(50)

,variable_name,definition,category,type
29,engineering_major_perc,Percentage of degrees awarded in Engineering.,academics,float
30,eng_tech_major_perc,Percentage of degrees awarded in Engineering T...,academics,float
31,language_major_perc,Percentage of degrees awarded in Foreign Langu...,academics,float
32,consumer_science_major_perc,Percentage of degrees awarded in Family And Co...,academics,float
33,law_major_perc,Percentage of degrees awarded in Legal Profess...,academics,float
34,english_major_perc,Percentage of degrees awarded in English Langu...,academics,float
35,liberal_arts_major_perc,Percentage of degrees awarded in Liberal Arts ...,academics,float
36,library_science_major_perc,Percentage of degrees awarded in Library Science.,academics,float
37,bio_science_major_perc,Percentage of degrees awarded in Biological An...,academics,float
38,math_stats_major_perc,Percentage of degrees awarded in Mathematics A...,academics,float
39,military_major_perc,Percentage of degrees awarded in Military Tech...,academics,float
40,interdiscipline_major_perc,Percentage of degrees awarded in Multi/Interdi...,academics,float
41,parks_rec_major_perc,"Percentage of degrees awarded in Parks, Recrea...",academics,float
42,philo_relig_major_perc,Percentage of degrees awarded in Philosophy An...,academics,float
43,theology_major_perc,Percentage of degrees awarded in Theology And ...,academics,float
44,phys_science_major_perc,Percentage of degrees awarded in Physical Scie...,academics,float
45,science_technician_major_perc,Percentage of degrees awarded in Science Techn...,academics,float
46,psych_major_perc,Percentage of degrees awarded in Psychology.,academics,float
47,protective_services_major_perc,Percentage of degrees awarded in Homeland Secu...,academics,float
48,public_admin_major_perc,Percentage of degrees awarded in Public Admini...,academics,float
49,social_science_major_perc,Percentage of degrees awarded in Social Sciences.,academics,float
50,construction_major_perc,Percentage of degrees awarded in Construction ...,academics,float
51,mechanics_major_perc,Percentage of degrees awarded in Mechanic And ...,academics,float
52,precision_production_major_perc,Percentage of degrees awarded in Precision Pro...,academics,float
53,transportation_major_perc,Percentage of degrees awarded in Transportatio...,academics,float
54,vis_performing_arts_major_perc,Percentage of degrees awarded in Visual And Pe...,academics,float
55,health_medical_major_perc,Percentage of degrees awarded in Health Profes...,academics,float
56,business_marketing_major_perc,"Percentage of degrees awarded in Business, Man...",academics,float
57,history_major_perc,Percentage of degrees awarded in History.,academics,float
58,online_only,Flag for distance-education-only education,school,integer
59,part_time_percent,"Share of undergraduate, degree-/certificate-se...",student,float
60,pell_grant_rate,Percentage of undergraduates who receive a Pel...,aid,float
61,retention_rate,"First-time, full-time student retention rate a...",student,float
62,federal_loan_rate,The proportion of undergraduates who received ...,aid,float
63,median_debt,"Median debt of completers, suppressed for n=30",student,float
64,median_earnings,Median earnings of students working and not en...,aid,float
65,cost Average net price for Title IV institutions,aid,float,None
66,religious,Does the school have a religious affiliation?,school,integer
67,loan_ever,Share of students who received a federal loan ...,aid,float
68,pell_ever,Share of students who received a Pell Grant wh...,student,float
69,age_entry_avg,"Average age of entry, via SSA data",student,integer
70,female_share,"Share of female students, via SSA data",student,float
71,married_share,Share of married students,student,float
72,veteran_share,Share of veteran students,student,float
73,first_gen_share,Share of first-generation students,student,float
74,family_income_median,Median family income,student,integer
75,pct_born_us,Percent of the population from students' zip c...,student,float
76,poverty_rate,"Poverty rate, via Census data",student,float
77,unemployment_rate,"Unemployment rate, via Census data",student,float
78,not_working,Number of students not working and not enrolle...,earnings,float

In [23]:
college_data.head()

,id,institution_name,top_50,city,state,locale,control,pred_deg,highest_degree,historically_black,men_only,women_only,religious,sat_verbal_quartile_1,sat_verbal_quartile_2,sat_verbal_quartile_3,sat_math_quartile_1,sat_math_quartile_2,sat_math_quartile_3,sat_writing_quartile_1,sat_writing_quartile_2,sat_writing_quartile_3,agriculture_major_perc,resources_major_perc,architecture_major_perc,cultural_major_perc,communications_major_perc,comm_tech_major_perc,computer_science_major_perc,culinary_major_perc,education_major_perc,engineering_major_perc,eng_tech_major_perc,language_major_perc,consumer_science_major_perc,law_major_perc,english_major_perc,liberal_arts_major_perc,library_science_major_perc,bio_science_major_perc,math_stats_major_perc,military_major_perc,interdiscipline_major_perc,parks_rec_major_perc,philo_relig_major_perc,theology_major_perc,phys_science_major_perc,science_technician_major_perc,psych_major_perc,protective_services_major_perc,public_admin_major_perc,social_science_major_perc,construction_major_perc,mechanics_major_perc,precision_production_major_perc,transportation_major_perc,vis_performing_arts_major_perc,health_medical_major_perc,business_marketing_major_perc,history_major_perc,online_only,part_time_percent,pell_grant_rate,retention_rate,federal_loan_rate,median_debt,median_earnings,earnings_more_than_25k,cost,loan_ever,pell_ever,age_entry_avg,female_share,married_share,veteran_share,first_gen_share,family_income_median,pct_born_us,poverty_rate,unemployment_rate,not_working
0,100654,Alabama A & M University,False,Normal,AL,City: Midsize,Public,Predominantly bachelor's-degree granting,Graduate degree,True,False,False,False,370.0,410.0,450.0,350.0,400.0,450.0,NaN,NaN,NaN,0.0397,0.0199,0.0116,0.0000,0.0000,0.0348,0.0348,0.0,0.1490,0.1175,0.0348,0.0000,0.0281,0.0,0.0182,0.0546,0.0,0.1026,0.0199,0.0,0.0,0.0000,0.0000,0.0000,0.0248,0.0,0.0579,0.0050,0.0364,0.0480,0.0,0.0,0.0,0.0,0.0166,0.0000,0.1457,0.0000,False,0.0622,0.7115,0.6314,0.8204,33611.5,31400.0,0.462298,13415.0,0.93,0.81,20.629999,0.53,0.03,0.01,0.39,29039.0,94.739998,14.880000,4.84,201.0
1,100663,University of Alabama at Birmingham,False,Birmingham,AL,City: Midsize,Public,Predominantly bachelor's-degree granting,Graduate degree,False,False,False,False,520.0,580.0,640.0,520.0,585.0,650.0,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0018,0.0456,0.0000,0.0099,0.0,0.0862,0.0632,0.0000,0.0090,0.0000,0.0,0.0203,0.0262,0.0,0.0619,0.0135,0.0,0.0,0.0000,0.0095,0.0000,0.0181,0.0,0.0840,0.0280,0.0244,0.0501,0.0,0.0,0.0,0.0,0.0415,0.2090,0.1765,0.0212,False,0.2579,0.3505,0.8016,0.5397,23117.0,40300.0,0.660484,14805.0,0.92,0.59,22.670000,0.65,0.11,0.03,0.38,34909.0,96.500000,10.910000,3.45,352.0
2,100690,Amridge University,False,Montgomery,AL,City: Midsize,Private nonprofit,Predominantly bachelor's-degree granting,Graduate degree,False,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0411,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.6301,0.0,0.0000,0.0000,0.0,0.0,0.0000,0.0000,0.2603,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0685,0.0000,False,0.3727,0.6839,0.3750,0.7629,NaN,38100.0,0.646667,7455.0,0.97,0.70,32.820000,0.51,0.62,0.19,0.51,30037.0,94.089996,10.650000,3.60,41.0
3,100706,University of Alabama in Huntsville,False,Huntsville,AL,City: Midsize,Public,Predominantly bachelor's-degree granting,Graduate degree,False,False,False,False,510.0,575.0,640.0,510.0,580.0,650.0,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0318,0.0000,0.0273,0.0,0.0173,0.2566,0.0000,0.0173,0.0000,0.0,0.0309,0.0000,0.0,0.0855,0.0218,0.0,0.0,0.0000,0.0082,0.0000,0.0209,0.0,0.0218,0.0000,0.0000,0.0173,0.0,0.0,0.0,0.0,0.0346,0.1720,0.2247,0.0118,False,0.2395,0.3281,0.8098,0.4728,24738.0,46600.0,0.660566,17520.0,0.92,0.60,23.190001,0.55,0.17,0.04,0.34,39766.0,95.269997,9.370000,3.64,137.0
4,100724,Alabama State University,False,Montgomery,AL,City: Midsize,Public,Predominantly bachelor's-degree granting,Graduate degree,True,False,False,False,380.0,430.0,480.0,370.0,425.0,480.0,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0733,0.0000,0.0450,0.0,0.2150,0.0000,0.0000,0.0000,0.0000,0.0,0.0183,0.0000,0.0,0.1033,0.0183,0.0,0.0,0.0183,0.0000,0.0000,0.0150,0.0,0.0617,0.1183,0.0650,0.0150,0.0,0.0,0.0,0.0,0.0567,0.0633,0.1067,0.0067,False,0.0902,0.8265,0.6219,0.8735,33452.0,27800.0,0.342226,11936.0,0.94,0.85,20.889999,0.57,0.03,0.01,0.45,24029.5,94.529999,16.959999,4.81,251.0

In [19]:
college_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7308 entries, 0 to 7307
Data columns (total 81 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               7308 non-null   int64
 1   institution_name                 7308 non-null   object
 2   top_50                           7308 non-null   bool
 3   city                             7308 non-null   object
 4   state                            7308 non-null   object
 5   locale                           6931 non-null   object
 6   control                          7308 non-null   object
 7   pred_deg                         7308 non-null   object
 8   highest_degree                   7308 non-null   object
 9   historically_black               6934 non-null   object
 10  men_only                         6934 non-null   object
 11  women_only                       6934 non-null   object
 12  religious                        7308 non-null   bool
 13  sat_verbal_quartile_1            1294 non-null   float64
 14  sat_verbal_quartile_2            1294 non-null   float64
 15  sat_verbal_quartile_3            1294 non-null   float64
 16  sat_math_quartile_1              1308 non-null   float64
 17  sat_math_quartile_2              1308 non-null   float64
 18  sat_math_quartile_3              1308 non-null   float64
 19  sat_writing_quartile_1           790 non-null    float64
 20  sat_writing_quartile_2           790 non-null    float64
 21  sat_writing_quartile_3           790 non-null    float64
 22  agriculture_major_perc           6653 non-null   float64
 23  resources_major_perc             6653 non-null   float64
 24  architecture_major_perc          6653 non-null   float64
 25  cultural_major_perc              6653 non-null   float64
 26  communications_major_perc        6653 non-null   float64
 27  comm_tech_major_perc             6653 non-null   float64
 28  computer_science_major_perc      6653 non-null   float64
 29  culinary_major_perc              6653 non-null   float64
 30  education_major_perc             6653 non-null   float64
 31  engineering_major_perc           6653 non-null   float64
 32  eng_tech_major_perc              6653 non-null   float64
 33  language_major_perc              6653 non-null   float64
 34  consumer_science_major_perc      6653 non-null   float64
 35  law_major_perc                   6653 non-null   float64
 36  english_major_perc               6653 non-null   float64
 37  liberal_arts_major_perc          6653 non-null   float64
 38  library_science_major_perc       6653 non-null   float64
 39  bio_science_major_perc           6653 non-null   float64
 40  math_stats_major_perc            6653 non-null   float64
 41  military_major_perc              6653 non-null   float64
 42  interdiscipline_major_perc       6653 non-null   float64
 43  parks_rec_major_perc             6653 non-null   float64
 44  philo_relig_major_perc           6653 non-null   float64
 45  theology_major_perc              6653 non-null   float64
 46  phys_science_major_perc          6653 non-null   float64
 47  science_technician_major_perc    6653 non-null   float64
 48  psych_major_perc                 6653 non-null   float64
 49  protective_services_major_perc   6653 non-null   float64
 50  public_admin_major_perc          6653 non-null   float64
 51  social_science_major_perc        6653 non-null   float64
 52  construction_major_perc          6653 non-null   float64
 53  mechanics_major_perc             6653 non-null   float64
 54  precision_production_major_perc  6653 non-null   float64
 55  transportation_major_perc        6653 non-null   float64
 56  vis_performing_arts_major_perc   6653 non-null   float64
 57  health_medical_major_perc        6653 non-null   float64
 58  business_marketing_major_perc    6653 non-null   float64
 59  history_major_perc               6653 non-null   float64
 60  online_only                      6934 non-null   object
 61  part_time_percent                6643 non-null   float64
 62  pell_grant_rate                  6631 non-null   float64
 63  retention_rate                   2290 non-null   float64
 64  federal_loan_rate                6631 non-null   float64
 65  median_debt                      5957 non-null   float64
 66  median_earnings                  5317 non-null   float64
 67  earnings_more_than_25k           5591 non-null   float64
 68  cost                             6294 non-null   float64
 69  loan_ever                        5408 non-null   float64
 70  pell_ever                        5408 non-null   float64
 71  age_entry_avg                    5408 non-null   float64
 72  female_share                     5408 non-null   float64
 73  married_share                    5408 non-null   float64
 74  veteran_share                    5408 non-null   float64
 75  first_gen_share                  5405 non-null   float64
 76  family_income_median             5408 non-null   float64
 77  pct_born_us                      5367 non-null   float64
 78  poverty_rate                     5405 non-null   float64
 79  unemployment_rate                5405 non-null   float64
 80  not_working                      5704 non-null   float64
dtypes: bool(2), float64(67), int64(1), object(11)
memory usage: 4.4+ MB

In [20]:
college_data.head()

,id,institution_name,top_50,city,state,locale,control,pred_deg,highest_degree,historically_black,...,age_entry_avg,female_share,married_share,veteran_share,first_gen_share,family_income_median,pct_born_us,poverty_rate,unemployment_rate,not_working
0,100654,Alabama A & M University,False,Normal,AL,City: Midsize,Public,Predominantly bachelor's-degree granting,Graduate degree,True,...,20.629999,0.53,0.03,0.01,0.39,29039.0,94.739998,14.880000,4.84,201.0
1,100663,University of Alabama at Birmingham,False,Birmingham,AL,City: Midsize,Public,Predominantly bachelor's-degree granting,Graduate degree,False,...,22.670000,0.65,0.11,0.03,0.38,34909.0,96.500000,10.910000,3.45,352.0
2,100690,Amridge University,False,Montgomery,AL,City: Midsize,Private nonprofit,Predominantly bachelor's-degree granting,Graduate degree,False,...,32.820000,0.51,0.62,0.19,0.51,30037.0,94.089996,10.650000,3.60,41.0
3,100706,University of Alabama in Huntsville,False,Huntsville,AL,City: Midsize,Public,Predominantly bachelor's-degree granting,Graduate degree,False,...,23.190001,0.55,0.17,0.04,0.34,39766.0,95.269997,9.370000,3.64,137.0
4,100724,Alabama State University,False,Montgomery,AL,City: Midsize,Public,Predominantly bachelor's-degree granting,Graduate degree,True,...,20.889999,0.57,0.03,0.01,0.45,24029.5,94.529999,16.959999,4.81,251.0